main/static/css/myprofile.css
main/static/js/myprofile.js
main/templates/myprofile.html
main/templates/signin.html

Feature/signin )f

---

control/admin.py
control/apps.py
control/models.py
control/templates/control.html
control/tests.py
control/urls.py
control/views.py
myapp/settings.py
myapp/urls.py

관제페이지 만들었습니다
/control 입력하면 뜹니다

work_control

---

main/templates/home.html
main/templates/signin.html
main/urls.py
main/views.py
myapp/settings.py

feature: logout 구현

---

main/static/css/myprofile.css
main/static/js/myprofile.js
main/templates/myprofile.html

feature: 마이페이지 수정

---

main/forms.py
main/templates/myprofile.html
main/views.py
myapp/settings.py

Feature: 마이페이지 조회, 수정 구현

---

adminpanel/templates/adminpanel/user_list.html
adminpanel/views.py
main/templates/signin.html
main/templates/signup.html
main/views.py

회원가입 페이지 주소api 추가 및 관리자 페이지 수정

feat : 회원가입 페이지 주소api 추가 및 관리자 페이지 수정

---

main/templates/signup.html

feat: 회원가입 폼 수정

---

main/templates/myprofile.html
main/templates/signup.html

마이페이지 주소api연동 및 회원가입 페이지 주소api 입력수정

feat:마이페이지 주소api연동 및 회원가입 페이지 주소api 입력수정

---

control/templates/control.html
control/urls.py
control/utils.py
control/views.py

관제 이안류 API 해운대 완료

---

main/templates/home.html

feat :  home 수정

---

control/templates/control.html
control/utils.py
control/views.py

10개 해수욕장 이안류 반영

---

main/templates/cctv.html

feat : cctv 토글 키 수정 및 cctv창 비율조절

cctv창 비율조절

---

main/forms.py
main/templates/signup.html
main/views.py

feat : 회원가입창 양식 오류문구 수정

---

adminpanel/templates/adminpanel/admin_home.html
adminpanel/templates/adminpanel/notice_manage.html
adminpanel/templates/adminpanel/senario.html
adminpanel/templates/adminpanel/user_list.html
adminpanel/urls.py
adminpanel/views.py
main/templates/free_board.html

자유게시판 목록 생성 및 관리자 채널 공지사항, 자유게시판 관리 분리

feat:자유게시판 목록 생성 및 관리자 채널 공지사항, 자유게시판 관리 분리

---

main/forms.py
main/templates/forgotpw.html
main/templates/signin.html
main/templates/signup.html
main/urls.py
main/views.py

로그인 회원 가입 창 영문자 한글 변경 및 비밀번호 찾기 웹페이지 추가

feat: 로그인 회원 가입 창 영문자 한글 변경 및 비밀번호 찾기 웹페이지 추가

---

main/forms.py
main/models.py
main/urls.py

feat: 공지사항 새 글 작성 수정

---

adminpanel/templates/adminpanel/board_manage.html
adminpanel/templates/adminpanel/notice_manage.html
adminpanel/urls.py
adminpanel/views.py
main/views.py

관리자 페이지에서 공지사항 게시판, 자유 게시판 목록 조회 및 삭제 구현 완료

feat: 관리자 공지사항, 자유 게시판 조회, 삭제 기능

---

main/templates/board.html
main/templates/cctv.html
main/templates/chat.html
main/templates/free_board.html
main/templates/home.html
main/templates/myposts.html
main/templates/myprofile.html
main/templates/risk.html
main/templates/weather.html
main/urls.py
main/views.py

사이드바 마이페이지 버튼 내 정보 수정/ 내가 쓴 글 관리 드롭박스 표시 및 내 게시물 관리 페이지 추가

feat: 사이드바 마이페이지 버튼 내 정보 수정/ 내가 쓴 글 관리 드롭박스 표시 및 내 게시물 관리 페이지 추가

---

main/templates/chat.html
main/templates/home.html

홈 게시판 영역 크기 통일 및 모의훈련 페이지 채팅창과 평가창 틀 생성

feat: 홈 게시판 영역 크기 통일 및 모의훈련 페이지 채팅창과 평가창 틀 생성

---

adminpanel/templates/adminpanel/board_manage.html
adminpanel/templates/adminpanel/notice_manage.html
adminpanel/templates/adminpanel/user_list.html

관리자페이지 회원조회, 공지사항 및 자유게시판 관리 기능보완 완료

feat: 관리자페이지 회원조회, 공지사항 및 자유게시판 관리 기능보완

---

adminpanel/templates/adminpanel/board_manage.html
adminpanel/templates/adminpanel/notice_manage.html
adminpanel/templates/adminpanel/user_list.html

feat:관리자 게시판 인덱스번호 보완

---

control/templates/control.html
main/static/css/style.css

관제페이지 알림문자창, 콜 확인 팝업

---

main/templates/home.html
main/views.py

Home 게시판 DB연결 완료

---

main/templates/signup.html

feat: 회원가입 페이지 입력 값 실시간 오류 구문 출력

---

main/templates/new_post.html

feat 공지사항 글씨기 수정사항

---

control/utils.py
main/templates/board.html

feat 공지사항 글쓰기 새로운 페이지 이동

---

main/templates/board.html
main/templates/free_board.html
main/views.py

feat: 공지사항, 자유게시판 DB 연결

---

adminpanel/templates/adminpanel/user_list.html
adminpanel/views.py

feat:관리자 사용자 정보관리 삭제 버튼 추가

---

control/templates/control.html

관제창 야간지도로 변경

---

myapp/settings.py

feat:시스템 대한민국 시간 고정

---

main/templates/board.html

feat : 공지사항 네임 수정

---

main/templates/signup.html
main/templates/weather.html
main/views.py

날씨 페이지 드롭 다운 토글 키 추가 (강릉, 송정, 여수, 해운대)
회원 가입 시 바로 로그인 되어 HOME으로 가지는 경로를
회원 가입 완료 버튼으로 수정 후 HOME이 아닌 로그인 페이지로 가도록 경로 수정
태경이가 말한것도 추가 수정

feat: 날씨 페이지 드롭다운 토글 키 추가 및 회원가입시 로그인페이지로 가도록 경로 수정

---

main/templates/freeboard_detail.html
main/urls.py
main/views.py

feat: 자유게시판 자기 게시물 삭제

---

main/forms.py
main/templates/myprofile.html
main/templates/signup.html

회원 가입 창, 마이 페이지- 내 정보 수정 창에 상세 주소 창 추가
회원 가입 시 유효성 검사에서 계속 회원 가입창으로 새로고침 되길래 뭐가 문제인가 찾아보다가
생각해보니까 DB에 상세 주소 컬럼이 없어서 저장을 못하는 게 아닌가 생각됨
그래서 일단 주석 처리 하고 커밋 올립니다.

feat: 상세 주소 창 추가 (DB 컬럼 없어서 일단 주석 처리)

---

adminpanel/templates/adminpanel/user_list.html
main/templates/weather.html

feat:사용자 정보 관리 팝업 한글 변경

---

adminpanel/templates/adminpanel/board_manage.html
adminpanel/templates/adminpanel/notice_manage.html
main/templates/myposts.html

삭제 작업 시, '정말로 삭제하시겠습니까?' 팝업 띄우기

feat: 관리자(공지사항, 자유게시판), home(내게시물관리) 삭제 시, 팝업 창 띄우기

---

control/templates/control.html
control/utils.py
main/templates/home.html
main/utils.py
main/views.py

feat: home 마커 추가 및 API 예외처리

---

main/templates/home.html
main/templates/weather.html

home에 지도 크기랑 버튼 위치 변경 및
날씨 페이지에 스크립트 연동으로 주간 날씨 확인 가능하게 변경
문제점 
1. css 하기 복잡한 거 같다.(클래스 이름이나 버튼 지정 되어 있는 게 같이 지정 되있는 느낌)
예를 들어 홈에 버튼들의 크기를 늘리면 날씨 페이지나 게시판의 구분 토글 버튼도 커짐;
2. 날씨에 불러온 스크립트 정의 되지 않은 css는 내가 입력해서 적용되는 거 같은데 스크립트에서 정의가 이미 정의 한 거는 안 먹는 듯
위에 내용 관련 home.html 충돌 해결

fix: Home 페이지 충돌 해결 (home에 지도 크기랑 버튼 위치 변경 및 날씨 페이지에 스크립트 연동으로 주간 날씨 확인)

---

adminpanel/templates/adminpanel/admin_home.html
adminpanel/templates/adminpanel/board_detail.html
adminpanel/templates/adminpanel/senario.html

feat:관리자 홈 및 시나리오 관리 페이지 작성

---

main/templates/risk.html

feat: 위험도 페이지 틀 생성

---

control/templates/control.html
control/utils.py
control/views.py
main/static/css/style.css

feat: 관제 경고알람 시간 추가

---

adminpanel/templates/adminpanel/admin_home.html
adminpanel/templates/adminpanel/board_detail.html
adminpanel/templates/adminpanel/board_manage.html
adminpanel/templates/adminpanel/create_notice.html
adminpanel/templates/adminpanel/csv_upload.html
adminpanel/templates/adminpanel/notice_detail.html
adminpanel/templates/adminpanel/notice_manage.html
adminpanel/templates/adminpanel/senario.html
adminpanel/templates/adminpanel/user_list.html
adminpanel/urls.py
adminpanel/views.py

관리자 경로수정
네비바 수정
상단바에 관제, 메인 홈 가는 버튼 생성

feat:관리자 경로 및 네비바 기능 추가

---

main/templates/board.html
main/templates/board_detail.html
main/templates/cctv.html
main/templates/chat.html
main/templates/create_freeboard.html
main/templates/free_board.html
main/templates/freeboard_detail.html
main/templates/home.html
main/templates/myposts.html
main/templates/myprofile.html
main/templates/risk.html
main/templates/weather.html

main폴더 전체html 네비 통일 및 경로 연결
main폴더 각 페이지별 틀 보완
로그인 권한 별 관리자,관제,메인 이동 버튼 생성

feat:main폴더 전체html 네비 통일 및 경로 연결

---

main/static/css/style.css
main/templates/signin.html
main/templates/signup.html

로그인(아웃) 박스 길이조절

---

main/templates/create_freeboard.html
main/templates/freeboard_detail.html
main/templates/myprofile.html
main/urls.py

feat:마이페이지 토글 문제점 해결 및 경로 정상화

---

main/templates/weather.html
main/views.py

날씨 페이지 주간 날씨 스크립트
장소에 따라 변경 가능하게 수정 
**문제점은 스크립트에 없는 지역 존재
현재 대천은 바로 인근 해수욕장인 보령으로 스크립트 불러왓고
고래불 해수욕장 (영덕) - 스크립트 존재 x -> 현재 강원 스크립트 지정
경북도 영덕도 존재하지않음..
스크립트 창 크기 수정 완료

feat: 날씨 페이지 주간 날씨 스크립트 장소에 따라 변경 가능하게 수정 및 스크립트 창 크기 조절

---

control/templates/control.html

feat: 알림창 고침

---

adminpanel/templates/adminpanel/notice_manage.html
requirements.txt

Feat: 관리자 공지사항 삭제

---

main/templates/signup.html

회원가입 창 
숫자만 입력해도 하이푼(-) 자동 입력
000-0000-0000 자릿수 초과 시 입력 제한

feat: 회원가입 창 숫자만 입력해도 하이푼(-) 자동 입력 및 000-0000-0000 자릿수 초과 시 입력 제한

---

adminpanel/views.py

Feat: 관리자 자유 게시판 카테고리 기능 수정

---

main/templates/weather.html
main/views.py

Feat: 날씨 카테고리 수정

---

main/templates/create_freeboard.html
main/templates/free_board.html
main/templates/freeboard_detail.html
main/templates/home.html

footer위치 수정

---

control/templates/control.html

control페이지 cctv버튼 생성

---

adminpanel/templates/adminpanel/board_detail.html
adminpanel/templates/adminpanel/notice_detail.html
adminpanel/views.py
main/templates/board_detail.html
main/templates/freeboard_detail.html
main/views.py

Feat: 파일 업로드 추가

---

main/templates/agreement.html

chore: 개인정보 수집 및 동의 텍스트 변경

---

control/templates/control.html
main/static/css/style.css

control 페이지 cctv모달창

---

control/templates/control.html
control/utils.py
control/views.py

feat: 이안류 api 완료

---

control/apps.py

feat: job 테이블 생성 완료

---

control/templates/control.html

feat:관제창 네비바 수정

---

main/static/css/style.css
main/templates/home.html

feat: css버튼 호버 오류 수정

---

control/templates/control.html
main/templates/home.html

feat: 이안류 api 비동기 home 적용

---

adminpanel/templates/adminpanel/admin_home.html
adminpanel/templates/adminpanel/board_manage.html
adminpanel/templates/adminpanel/create_notice.html
adminpanel/templates/adminpanel/notice_detail.html
adminpanel/templates/adminpanel/notice_manage.html
adminpanel/templates/base/admin_base.html

feat: 관리자 페이지 footer및 수정 보완

---

control/templates/control.html
main/static/css/style.css

control call버튼 토글 디자인 수정

---

main/templates/board_detail.html

feat: 메인홈 게시판 footer 고정

---

control/templates/control.html
control/urls.py
control/views.py

feat: yolo web 붙이기 초안 완성

---

control/templates/control.html
control/urls.py
control/views.py

DB에 저장된 cctv 영상으로 yolo 적용 후 관제 페이지 송출

feat: 관제 cctv DB로 불러와서 yolo 적용

---

control/templates/control.html

feat: yolo 적용 창 크기 조절

---

control/templates/control.html

openweather API로 control 페이지 날씨 연결했습니다.
javascript, html로 연결

feat : control.html (기상예보 모달)

---

control/views.py

feat: 새로운 yolo 모델

---

control/templates/control.html
control/views.py

Feat: 날씨 api key 삭제

---

control/templates/control.html
main/static/css/style.css

control css수정

---

adminpanel/templates/base/admin_base.html

feat: 메인, 관리자 footer 통일

---

adminpanel/templates/adminpanel/senario.html
adminpanel/views.py

feat: 시나리오 필터기능 완료

---

adminpanel/templates/adminpanel/senario.html

feat: 필터기능 고치기

---

main/views.py

feat: 날씨 디폴트 값 설정

---

control/views.py

feat: yolo 새로운 버전 web에 붙이기

---

control/views.py

feat: 바운딩 박스 색깔 별로 사람 수 세기

---

control/templates/control.html
control/views.py
requirements.txt

feat: requirements update

---

adminpanel/static/js/main.js
adminpanel/templates/adminpanel/admin_home.html
adminpanel/urls.py
adminpanel/views.py
main/models.py

Feat: 관리자 홈 그래프

---

control/templates/control.html

feat: 관제창 날씨 디폴트 지정

---

control/templates/control.html

cctv 모달 닫기 버튼 클릭 시, 사람 detect 및 count 종료

feat: 사람 detect 및 count 닫기 버튼 클릭 시 종료

---

control/views.py

feat: yolo 새로운 버전

---

main/templates/chat.html

feat : 해양안전 시나리오 챗봇 채팅 메세지, 스톱워치 추가

feat : 챗봇 채팅 메세지, 스톱워치 추가

---

adminpanel/static/js/main.js
adminpanel/templates/adminpanel/admin_home.html
adminpanel/views.py
control/views.py

Feat: 관리자 홈 기능 수정

---

adminpanel/views.py

Feat:  메세지 기록 조회 수정

---

adminpanel/templates/adminpanel/admin_home.html

Feat : 관리자 홈 캘린더 삭제

---

main/templates/chat.html

feat: 시나리오 챗봇 초안 v2

---

adminpanel/views.py

feat: csv 업로드 오류 수정

---

adminpanel/views.py

feat: csv datetime 오류 수정

---

main/templates/signin.html
main/urls.py
main/views.py

Feat : 로고 버튼 자동 로그인

---

control/templates/control.html
main/templates/chat.html

메인 생성형ai 데이터 하드코딩 및 관제 훈련 시나리오 생성형ai  모달 적용

feat: 메인 생성형ai 데이터 하드코딩 및 관제 훈련 모달 적용

---

adminpanel/templates/adminpanel/csv_upload.html

csv페이지에서 csv 업로드 하는 동안 업로드 버튼 옆에 로딩-스피너 생성

feat: csv 업로드 페이지 로딩 기능 추가

---

adminpanel/static/css/style.css
adminpanel/templates/adminpanel/board_manage.html
adminpanel/templates/adminpanel/create_notice.html
adminpanel/templates/adminpanel/notice_manage.html
adminpanel/templates/adminpanel/senario.html
adminpanel/templates/adminpanel/user_list.html
adminpanel/templates/base/admin_base.html
main/static/css/style.css
main/templates/base/base.html
main/templates/board.html
main/templates/chat.html
main/templates/create_freeboard.html
main/templates/free_board.html
main/templates/freeboard_detail.html
main/templates/myposts.html
main/templates/myprofile.html
main/templates/weather.html

footer_css 수정

---

control/views.py

관제 페이지 중문 해수욕장 cctv에 맞게끔 yolo 적용

feat: 관제 중문 해수욕장 cctv yolo 적용

---

control/templates/control.html

feat: yolo 실행 멘트 추가

---

adminpanel/views.py

feat: csv 업로드 오류 해결

---

main/templates/chat.html

feat: 메인 챗봇창 새로고침 리셋 기능, 피서객 안전 수정

feat: 메인 챗봇창 새로고침 리셋 기능, 피서객 안전 수정

---

control/templates/control.html

feat: 관제 시나리오 챗봇 DB 연결

---

adminpanel/templates/adminpanel/user_list.html
adminpanel/utils.py
adminpanel/views.py

feat: 관리자 창 사용자 정보 마스킹

---

control/templates/control.html
control/views.py

feat: 관제 페이지 현재 시각 띄우기

---

control/templates/control.html
main/static/css/style.css

feat: 관제 페이지 시각 위치 변동

---

adminpanel/templates/adminpanel/user_detail.html
adminpanel/templates/adminpanel/user_list.html
adminpanel/urls.py
adminpanel/views.py

관리자 페이지 사용자 정보관리에서 user 이름 클릭 시, 세부사항 정보 띄우기

feat: 관리자 페이지 user 정보 세부사항

---

main/templates/myprofile.html

feat: 내정보 수정 이미지 업로드 기능 삭제

---

adminpanel/templates/adminpanel/admin_home.html
main/static/css/style.css

관리자 페이지 크기 통일 및 일반페이지 사이드바 오류 수정

feat: 관리자 페이지 크기 통일 및 일반페이지 사이드바 오류 수정

---

adminpanel/templates/base/admin_base.html
control/templates/control.html

footer 로고, 관제 cctv 수정

---

main/static/css/style.css

fix: 관제페이지 타이머 색깔 및 크기 수정

---

main/templates/chat.html

fix : 시나리오 페이지 최종시간 변경

---

main/templates/signup.html

feat: 주소 제외 에러문구 띄우기 완료

---

main/templates/signup.html

feat: 회원가입 주소창 오류 멘트 완료

---

adminpanel/templates/base/admin_base.html
main/templates/base/base.html

feat: 메인, 관리자 페이지 사용자 27조 김*리 처럼 마스킹 완료

feat: 메인, 관리자 페이지 사용자 27조 김*리 처럼 마스킹 완료
